### ISSUE TITLE
Can't sync a followed manga

### ISSUE THREAD

**Issue by MoaYenrai** [FaizanDurrani/Paperback-Public#42]
**Describe the bug**
When I sync my followlist, I get the message: "You have 1 manga (s) that are not followed locally". However, a click on "Follow locally" is useless because the message reappears every time I sync.

Apparently I can no longer access the manga on MangaDex. It was still on my reading list.
(URL: https://mangadex.org/title/42110/the-archmage-s-daughter)

**To Reproduce**
Add 42110 to your follow list
Go to the Follows tab
Sync with MD

**Expected behaviour**
A full sync with MD

**App Version**
v0.2-wip.4

**Comment by FaizanDurrani** [comment]
Should be fixed, added restricted mangas to the database
