### ISSUE TITLE
[REQUEST] Jump back to search instead of homepage on info page exit

### ISSUE THREAD

**Issue by ZhongDev** [FaizanDurrani/Paperback-Public#66]
**Description**
Make any info screens opened from search menu to return to the search screen first then back to home screen

**How would it improve the App?**
For series that have multiple mangas/spinoffs (e.g. Konosuba) it is annoying when trying to go through every item in the search. e.g. looking at description of the spinoffs and marking then for read etc.

**Additional context**

**Comment by FaizanDurrani** [comment]
Another one of SwiftUI quirks.
SwiftUI doesn't actually support the built-in search bar hence the current solution has very limited functionality.

Closing the issue until official support from Apple drops to support the search bar.
