### ISSUE TITLE
[BUG] Specific manga doesn’t show correct chapters

### ISSUE THREAD

**Issue by SirNoodly** [FaizanDurrani/Paperback-Public#68]
**Describe the bug**
Tower of God doesn’t load all the correct chapters (and chapter info) that are visible/available on Mangadex. 

**To Reproduce**
1. Open app. 
2. Search Tower of God and select first result. 
3. Scroll down and view chapter list. 

**Expected behaviour**
The chapter and chapter info visible on mangadex is what should be seen in the app. 

**App Version**
App: v0.2-wip.7.1
iOS: 13.4.1

**Screenshots**
![E68E9919-072B-443E-8A93-BB3259E960E7](https://user-images.githubusercontent.com/55963821/80052044-ae038700-84e7-11ea-8942-dc1e04e7f4b3.png)
![655E5AAB-E43C-4411-90F3-6F70E264E910](https://user-images.githubusercontent.com/55963821/80052051-b1970e00-84e7-11ea-920b-c0c3bde3cbe9.png)
![29D50D49-475E-4002-8E12-04D229F0E5FA](https://user-images.githubusercontent.com/55963821/80052180-0a66a680-84e8-11ea-9391-88aefd9c2f3d.png)

**Comment by FaizanDurrani** [comment]
Was using manga as placeholder to test UI forgot to remove it from build.
