### ISSUE TITLE
[BUG] persistent message

### ISSUE THREAD

**Issue by Microscale** [FaizanDurrani/Paperback-Public#73]
**Describe the bug**
https://youtu.be/b0MAxXw52Fw
At 3:20 it starts bugging and keeps telling me I have different lists on manga dex and paper reader, it persists no matter what I choose.

**To Reproduce**
Idk it just started happening when I changed a manga and won’t stop asking me now.

**Expected behaviour**
When I choose an option it should override the other and not show up persistently.

**App Version**
v0.2.1-r1

**Screenshots**
https://youtu.be/b0MAxXw52Fw
Bug starts at 3:20 and persists, prevents me from using the app.

**Comment by FaizanDurrani** [comment]
This should be fixed now
