### ISSUE TITLE
[BUG] App Crashes upon tapping View all Chapters

### ISSUE THREAD

**Issue by HellDuke-Astaroth** [FaizanDurrani/Paperback-Public#75]
The moment I tap on View all Chapters, the app crashes. Although it seems to regain functionality after a few more tries.

**App Version**
v0.2-wip.3.1

**Comment by FaizanDurrani** [comment]
Let me know if the latest Beta fixes this or not

**Comment by HellDuke-Astaroth** [comment]
The bug still occurs for me in the newest beta.
