### ISSUE TITLE
[BUG] Chapter list/description bugged in multi view(smallest) and slide over 

### ISSUE THREAD

**Issue by thelazyaxias** [FaizanDurrani/Paperback-Public#83]
![0D00B71B-0E7D-47D4-AE5A-7B90E83F7658](https://user-images.githubusercontent.com/64099655/80282031-72e39c80-870f-11ea-9679-afe6683bdd23.png)
![2421CFE4-C43B-4208-B078-8C9A052F317D](https://user-images.githubusercontent.com/64099655/80282056-9870a600-870f-11ea-91a9-287dd5ca03e1.png)

**Describe the bug**
Chapter list and manga description doesn’t display properly in the smallest multi view and slide over mode. Horizontal and vertical are bugged 

**To Reproduce**
Open the app in the smallest multi view panel or slide over 

**App Version**
Eg: v0.3-b2

**Screenshots**

**Comment by FaizanDurrani** [comment]
Should be fixed with #78
