### ISSUE TITLE
[REQUEST] Ability to change the sort order of the chapter list

### ISSUE THREAD

**Issue by FaizanDurrani** [FaizanDurrani/Paperback-Public#9]
Currently, this can only be done by adding an option in the settings. Real-time sorting won't be possible until a feature is added into MD API

**Comment by Sai-P** [comment]
Yeah it's fine if it's not real-time, but having an app-side sort option in the library page is already a good start

**Comment by FaizanDurrani** [comment]
Added in v0.3-b2
