### ISSUE TITLE
[REQUEST] Seamless two-way sinc between MD and app

### ISSUE THREAD

**Issue by an0thercat** [FaizanDurrani/Paperback-Public#92]
**Description**

When you add a manga to a list or move a manga from a list to another in MD, you then respectively get the following messages in the app:
- Manga not followed locally: _Follow locally_ or _Unfollow from MD_.
- Manga conflicts: _Use Local_ or _Use MD_.

After you follow a manga in MD, I think you'd always expect it to be followed in the app as well, thus always _Follow locally_.
After you move or unfollow a manga in MD, I think you'd always expect it to be moved or unfollowed in the app as well, thus always _Use MD_.

Can the syncing process in the app be made more seamless, i.e. without the need for confirmation messages?

**How would it improve the App?**

Less friction and less risk of making a mistake when the app is syncing.

E.g., when you add a manga to a list or move a manga from a list to another in the app, it instantly syncs in MD and you don't need to think about it.

**Additional context**

![IMG_1944](https://user-images.githubusercontent.com/15112976/80403749-ca793800-88c8-11ea-8242-9078e952180b.jpeg)

![IMG_1945](https://user-images.githubusercontent.com/15112976/80403761-cfd68280-88c8-11ea-85c4-ba886623ca69.jpeg)

**Comment by FaizanDurrani** [comment]
This is by design and cannot be streamlined, I can't assume the user's actions and the app has no idea something changed on MD, it only knows that there's a discrepancy between app's list and MDList.
