### ISSUE TITLE
[REQUEST] Background refresh

### ISSUE THREAD

**Issue by an0thercat** [FaizanDurrani/Paperback-Public#96]
**Description**

Just to build on your answer regarding issue #92:

- Is it be possible to have Fetching MDList screen operating in the background, so it doesn't prevent you from navigating the app at the same time?

- For users like me who are sure they want to follow a certain action whenever there’s a discrepancy (like _Follow locally_, _Use MD_, _Remove local manga_), is it be possible to automate these actions as toggle options in the sync settings?

- If not, at least would it be possible to name the mangas in question so we know which ones are concerned?

Manually adjusting lists can be confusing when you often switch between multiple devices. You don’t necessarily remember what manga you added/moved on which device, and if you’re not sure, the result might not match what you intended.

**How would it improve the App?**

I don't know the technical constraints, but I hope it is possible to have an effortless two-way sync (or as close as possible), like previously between MR website and app (or between AniList and its supported apps etc.)

Thank you.

**Comment by FaizanDurrani** [comment]
> Is it be possible to have Fetching MDList screen operating in the background, so it doesn't prevent you from navigating the app at the same time?

Again, this was done so that there isn't accidental data loss.

> For users like me who are sure they want to follow a certain action whenever there’s a discrepancy (like Follow locally, Use MD, Remove local manga), is it be possible to automate these actions as toggle options in the sync settings?

I have considered this option and will look to implement in the future builds.

> If not, at least would it be possible to name the mangas in question so we know which ones are concerned?

This is also in consideration whether a list of all the manga should show up or not.

I would advise you to open different requests for these 2 features.
